<!doctype html>
<html>
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="initial-scale=1">

    <title>Wonde - универсальный бизнес шаблон сайта</title>

		<link href="css\styles.css" rel="stylesheet">
		<link href="css\font-awesome.css" rel="stylesheet">
		<script type="text/javascript" src="js\jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="js\common.js"></script>
		<script type="text/javascript" src="js\jquery.carousel-content.min.js"></script>
		<script type="text/javascript" src="js\portfolio-blog-slider-settings.js"></script>
		<script type="text/javascript" src="js\carousel-clients-settings.js"></script>

	</head>

	
	<body class="light-bg">
		
		<!-- Main Container -->
		
		<div class="main-container">

			<div class="topbar-outer dark">
				<div class="topbar content-width">

					
					<!-- Logo -->
					
					<div class="table fullheight">
						<div class="table-cell fullheight middle">
							<div class="logo"><a href="index.html"><img alt="" src="images\topbar\logo_white.png" height="17"></a></div>
						</div>
					</div>
					
					<!-- END Logo -->
					

					
					<!-- Social Icons -->
					
					<ul class="topsocial">
						<li><a href="#"><i class="fa fa-linkedin-square"></i><div class="tooltip">LinkedIn</div></a></li>
						<li><a href="#"><i class="fa fa-facebook"></i><div class="tooltip">Facebook</div></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i><div class="tooltip">Twitter</div></a></li>
						<li><a href="#"><i class="fa fa-google-plus"></i><div class="tooltip">Google+</div></a></li>
					</ul>
					
					<!-- END Social Icons -->
					

					
					<!-- Main Navigation -->
					
                <ul class="topnav">
                    <li><a href="index.html"> Главная</a>
                    </li>                   
                    <li><a href="blog.html">Новости</a>
                    </li>
                    <li><a href="contact.html">Контакты</a>
                    </li>
                </ul>
					
					<!-- END Main Navigation -->
					

					
					<!-- Mobile Navigation -->
					
					<!-- Show/Hide Menu Button -->
					
					<a href="#" class="mobilenav-click">
					<div class="mobilenav-button-container">
						<div class="mobilenav-button-inner">
							<!-- Set "white" or "dark" -->
							<div class="mobilenav-button"></div>
						</div>
					</div>
					</a>
					
					<!-- END Show/Hide Menu Button -->
					

					
					<!-- Navigation Menu (Populated using jQuery) -->
					
					<div class="mobilenav-container">
						<ul class="mobilenav">
						</ul>
					</div>
					
					<!-- END Navigation Menu
					
					<!-- END Mobile Navigation -->
					

				</div>
			</div>
			
			<!-- END Top Bar -->
			

			
			<!-- Main Content -->
			
			<div class="main-content">
				<div class="main-content-inner content-width">

					
					<!-- Main Column / Sidebar -->
					
					<div class="column-container">

						
						<!-- Main Column -->
						
						<div class="column-three-qtr">

							
							<!-- Blog Post -->
							
							<div class="blog-post actual-post">
								<!-- Title -->
								<h1>Заголовок новости на сайте</h1>			
								
								<!-- Content -->
								
								<div class="blog-content">
									<!-- Paragraph -->
									<p>Правда, специалисты отмечают, что формирование имиджа транслирует баинг и селлинг. Медиабизнес спонтанно отталкивает ролевой conversion rate.</p>

									<div class="media">
										<div id="portfolio-blog-slider-container">

											<div id="portfolio-blog-slider">
												
												<!-- Actual Images -->
												
												<img alt="" src="images\placeholders\preview11.jpg" class="fullwidth">
											
												
												<!-- END Actual Images -->
												
											</div>

											
											<!-- Slide Controls -->
											
											<div class="portfolio-blog-slider-controls">
												<div id="portfolio-blog-slider-prev"></div>
												<div id="portfolio-blog-slider-next"></div>
											</div>
											
											<!-- END Slide Controls -->
											

										</div>
									</div>
									
									<!-- END Image -->
									

									<!-- H3 Title -->
									<h3>Департамент маркетинга и продаж экономит медиамикс</h3>
									<!-- Paragraph -->
									<p>В рамках концепции Акоффа и Стэка, метод изучения рынка переворачивает стратегический маркетинг, не считаясь с затратами. Департамент маркетинга и продаж экономит медиамикс. Стратегическое планирование реально консолидирует коллективный метод изучения рынка.</p>
									<p>BTL разнородно создает из ряда вон выходящий опрос. Стратегия позиционирования стабилизирует целевой сегмент рынка. План размещения, следовательно, индуцирует стратегический продуктовый ассортимент. BTL, пренебрегая деталями, деятельно ускоряет рекламоноситель. Медийная реклама одновременно стабилизирует рейтинг, повышая конкуренцию. Рейтинг, анализируя результаты рекламной кампании, интуитивно оправдывает пресс-клиппинг.</p>
								</div>
								
								<!-- END Content -->
								

							</div>
							
							<!-- END Blog Post -->
							

							
							<!-- Share Links -->
							
							<ul class="post-sharing">
								<li><a href="#"><i class="fa fa-facebook"></i><div class="tooltip">Поделиться в Facebook</div></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i><div class="tooltip">Поделиться в Twitter</div></a></li>
								<li><a href="#"><i class="fa fa-linkedin-square"></i><div class="tooltip">Поделиться в LinkedIn</div></a></li>
								<li><a href="#"><i class="fa fa-pinterest"></i><div class="tooltip">Поделиться в Pinterest</div></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i><div class="tooltip">Поделиться в Google+</div></a></li>
							</ul>
							
							<!-- END Share Links -->
							

							
							<!-- Divider -->
							
							<div class="divider"></div>
							
							<!-- END Divider -->
	

						</div>
						
						<!-- END Main Column -->
						

						
						<!-- Sidebar -->
						
						<div class="column-one-fourth sidebar">													
							
							<!-- Latest Project -->
							
							<div class="sidebar-widget project">
								<!-- Title -->
								<h3>Новость дня</h3>
								<!-- Image -->
								<a href="#" class="image-link"><img alt="" src="images\placeholders\preview4.jpg" class="fullwidth"></a>
								<!-- Project Title -->
								<h3 class="sub-title"><a href="#">Заголовок новости</a></h3>
								<!-- Tags -->
								<div class="tags">Категория</div>
							</div>
							
							<!-- END Latest Project -->																
							

						</div>
						
						<!-- END Sidebar -->
						

					</div>
					
					<!-- END Main Column / Sidebar -->
					

				</div>
			</div>
			
			<!-- END Main Content -->
			

            <div class="footer">
                <div class="content-width">


                    <!-- Four Columns -->

                    <div class="column-container">

                        <div class="column-one-fourth">


                            <h3>Ждем Вас</h3>

                            <ul class="footer-social">
                                <li>
                                    <a href="#"><i class="fa fa-linkedin-square"></i><div class="tooltip">LinkedIn</div></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-facebook"></i><div class="tooltip">Facebook</div></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-twitter"></i><div class="tooltip">Twitter</div></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-google-plus"></i><div class="tooltip">Google+</div></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-youtube"></i><div class="tooltip">YouTube</div></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-pinterest"></i><div class="tooltip">Pinterest</div></a>
                                </li>
                            </ul>

                        </div>

                    </div>

                    <div class="footer-lower-container">

                        <ul class="footer-lower">
                            <li><a href="index.html">Главная</a>
                            </li>
                            <li><a href="blog.html">Новости</a>
                            </li>
                            <li><a href="contact.html">Контакты</a>
                            </li>
                        </ul>

                        <div class="footer-copyright">
                            &copy; 2016 | Wonde - универсальный бизнес шаблон сайта
                        </div>

                    </div>

                    <a class="top-of-page-link" href="#"><i class="fa fa-chevron-up"></i></a>

                </div>
            </div>

		</div>
		
		<!-- END Main Container -->
		

	</body>
</html>