<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1">
    <title>Wonde - универсальный бизнес шаблон сайта</title>

    <link href="css\styles.css" rel="stylesheet">
    <link href="css\font-awesome.css" rel="stylesheet">

    <script type="text/javascript" src="js\jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="js\common.js"></script>
    <script type="text/javascript" src="js\jquery.carousel-main.min.js"></script>
    <script type="text/javascript" src="js\jquery.carousel-content.min.js"></script>
    <script type="text/javascript" src="js\home-slider-settings.js"></script>
    <script type="text/javascript" src="js\carousel-portfolio-settings.js"></script>
    <script type="text/javascript" src="js\carousel-blog-settings.js"></script>
    <script type="text/javascript" src="js\carousel-testimonials-settings.js"></script>
    <script type="text/javascript" src="js\carousel-clients-settings.js"></script>
</head>

<body class="light-bg home">
<div class="main-container">
    <div class="topbar-outer dark">
        <div class="topbar content-width">
            <div class="table fullheight">
                <div class="table-cell fullheight middle">
                    <div class="logo">
                        <a href="index.html"><img alt="" src="images\topbar\logo_white.png" height="17">
                        </a>
                    </div>
                </div>
            </div>

            <ul class="topsocial">
                <li><a href="#"><i class="fa fa-linkedin-square"></i><div class="tooltip">LinkedIn</div></a>
                </li>
                <li><a href="#"><i class="fa fa-facebook"></i><div class="tooltip">Facebook</div></a>
                </li>
                <li><a href="#"><i class="fa fa-twitter"></i><div class="tooltip">Twitter</div></a>
                </li>
                <li><a href="#"><i class="fa fa-google-plus"></i><div class="tooltip">Google+</div></a>
                </li>
            </ul>

            <ul class="topnav">
                <li><a href="index.html"> Главная</a>
                </li>
                <li><a href="blog.html">Новости</a>
                </li>
                <li><a href="contact.html">Контакты</a>
                </li>
            </ul>

            <a href="#" class="mobilenav-click">
                <div class="mobilenav-button-container">
                    <div class="mobilenav-button-inner">
                        <div class="mobilenav-button"></div>
                    </div>
                </div>
            </a>

            <div class="mobilenav-container">
                <ul class="mobilenav">
                </ul>
            </div>
        </div>
    </div>

    <div class="home-banner dark">

    </div>

    <div class="main-content">
        <div class="main-content-inner content-width">

            <div class="column-container">

                <div class="column-one-third">
                    <div class="icons-column">
                        <!-- Icon Backing -->
                        <div class="icon-backing" style="background-color: #916C6C;">
                            <!-- Icon -->
                            <i class="fa fa-heart"></i>
                        </div>
                    </div>
                    <div class="content-column">
                        <!-- Title -->
                        <h3>Дизайн</h3>
                        <!-- Text -->
                        <p>Интересно отметить, что каждая сфера рынка притягивает план размещения. </p>
                    </div>
                </div>

                <div class="column-one-third">
                    <div class="icons-column">
                        <!-- Icon Backing -->
                        <div class="icon-backing" style="background-color: #7089AD;">
                            <!-- Icon -->
                            <i class="fa fa-font"></i>
                        </div>
                    </div>
                    <div class="content-column">
                        <!-- Title -->
                        <h3>Верстка</h3>
                        <!-- Text -->
                        <p>Интересно отметить, что каждая сфера рынка притягивает план размещения. </p>
                    </div>
                </div>

                <div class="column-one-third">
                    <div class="icons-column">
                        <!-- Icon Backing -->
                        <div class="icon-backing" style="background-color: #63885F;">
                            <!-- Icon -->
                            <i class="fa fa-fullscreen"></i>
                        </div>
                    </div>
                    <div class="content-column">
                        <!-- Title -->
                        <h3>Разработка</h3>
                        <!-- Text -->
                        <p>Интересно отметить, что каждая сфера рынка притягивает план размещения. </p>
                    </div>
                </div>

            </div>

            <div class="divider"></div>

            <h3 class="section-title">Новости дня</h3>

            <div id="portfolio-nav" class="carousel-nav">
                <div class="back"></div>
                <div class="next"></div>
            </div>

            <div class="carousel">
                <ul id="portfolio-carousel" class="slider-container">

                 
                    <?php foreach ($IndexList as $indexItem):?>
                    <li class="column-one-fourth portfolio-item branding">
                                <p><img src="images\placeholders\<?php echo $indexItem['image'];?>"class="fullwidth" alt="" /></p>
                        <!-- Title -->
                        <h3><a href='/news/<?php echo $indexItem['id'] ;?>'><?php echo $indexItem['title'].' # '.$indexItem['id'];?></a></h3>
                        <!-- Tags -->
                        <div class="tags"><?php echo $indexItem['description'];?></div>
                    </li>
                    <?php endforeach;?>
                   
                    <!-- One Fourth -->


                    <!-- END One Fourth -->

                </ul>
            </div>

            <div class="column-container">
                <div class="column-three-qtr">
                    <div class="divider"></div>
                    <h3 class="section-title">Последние новости</h3>
                    <div id="blog-nav" class="carousel-nav">
                        <div class="back"></div>
                        <div class="next"></div>
                    </div>
                    <div class="carousel">
                        <ul id="blog-carousel" class="slider-container">

                            <?php foreach ($indexLastNews as $indexLastNewsItem):?>
                            <!-- One Fourth -->

                            <li class="column-one-fourth">
                                <!-- Image -->
                                <a href="/news/<?php echo $indexLastNewsItem['id'] ;?>" class="image-link"><img alt="" src="images\placeholders\<?php echo $indexLastNewsItem['image'] ;?>" class="fullwidth">
                                </a>
                                <!-- Title -->
                                <h3><a href='/news/<?php echo $indexLastNewsItem['id'] ;?>'><?php echo $indexLastNewsItem['title'].' # '.$indexLastNewsItem['id'];?></a></h3>
                                <!-- Date -->
                                <div class="date"><?php echo $indexLastNewsItem['date'] ;?></div>
                                <!-- Excerpt -->
                                <p><?php echo $indexLastNewsItem['content'] ;?></p>
                                <!-- Read More Link -->
                                <a href='/news/<?php echo $indexLastNewsItem['id'] ;?>'>Подробнее</a>
                            </li>

                            <!-- END One Fourth -->
                            <?php endforeach;?>

                        </ul>
                    </div>

                </div>

                <div class="column-one-fourth">

                    <div class="divider"></div>




                </div>

            </div>

        </div>
    </div>

    <div class="footer-container">

        <div class="spacer"></div>

        <div class="content-width">
            <div class="client-logos-container">

                <div class="client-logos-title">
                    <span>Наши партнеры</span>
                </div>

                <div id="clients-back"></div>
                <div id="clients-next"></div>

                <div class="carousel">
                    <ul id="clients-carousel" class="column-container">
<?php
foreach ($logoPictures as $soloLogo):
?>
                        <li class="">
                            <div class="logo-outer">
                                <div class="logo-inner">
                                    <!-- Actual Logo -->
                                    <img alt="" src="images\client-logos\<?php echo $soloLogo ?>">
                                </div>
                            </div>
                        </li>
<?php endforeach;?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="footer-infobar">
            <div class="content-width">
                <!-- Text -->
                Мы предоставляем только проверенную информацию. Все права защищены.
            </div>
        </div>

        <div class="footer">
            <div class="content-width">


                <!-- Four Columns -->

                <div class="column-container">

                    <div class="column-one-fourth">


                        <h3>Ждем Вас</h3>

                        <ul class="footer-social">
                            <li>
                                <a href="#"><i class="fa fa-linkedin-square"></i><div class="tooltip">LinkedIn</div></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i><div class="tooltip">Facebook</div></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i><div class="tooltip">Twitter</div></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-google-plus"></i><div class="tooltip">Google+</div></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-youtube"></i><div class="tooltip">YouTube</div></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-pinterest"></i><div class="tooltip">Pinterest</div></a>
                            </li>
                        </ul>

                    </div>

                </div>

                <div class="footer-lower-container">

                    <ul class="footer-lower">
                        <li><a href="index.html">Главная</a>
                        </li>
                        <li><a href="blog.html">Новости</a>
                        </li>
                        <li><a href="contact.html">Контакты</a>
                        </li>
                    </ul>

                    <div class="footer-copyright">
                        &copy; 2016 | Wonde - универсальный бизнес шаблон сайта
                    </div>

                </div>

                <a class="top-of-page-link" href="#"><i class="fa fa-chevron-up"></i></a>

            </div>
        </div>

    </div>

</div>

</body>

</html>